#! /usr/bin/python
from argparse import ArgumentParser, REMAINDER
from sys import exit


if __name__ == '__main__':
	import main
	from program import get_programs

	parser = ArgumentParser()
	parser.add_argument('program', type=str, default='help')
	parser.add_argument('prog_args', nargs=REMAINDER)
	args = parser.parse_args()

	programs = get_programs()
	if args.program not in programs.keys():
		print(f"usage: {parser.prog} <command> [command_args]")
		print("\ncommand is one of:")
		for p in programs.items():
			print(f'    {p[0]}    {p[1].description}')
		exit(1)

	print(f'[I] running {args.program}...')
	prog = programs[args.program](args.prog_args)

